### ISSUE TITLE
Incorrect Global ID 

### ISSUE THREAD

**Issue by justusjonas74** [highsource/vgn-stops#1]
I'm not sure but I guess the concept of global ids doesn't allow any leading zero. 
de:**09472**:23351 should be de:**9472**:23351

**Comment by highsource** [comment]
This is what I get from the backend. I can correct it but not sure if it is the right thing to do. I'll have to check the DHID specification ([VDV Schrift 432](https://www.vdv.de/service/downloads.aspx?id=101502&forced=true)).

By the way this middle part is actually "Kreisschlüssel".

**Comment by justusjonas74** [comment]
The specs says: "Im Kreisschlüssel sind ggf. vorhandene führende Nullen beizubehalten.". So 09472 is correct formatted. I was wrong.

**Comment by highsource** [comment]
The problem is still that some providers cut the zeroes. So actually I should leftpad this middle part. But then the ids may be rejected by the provider itself (if they'd just do string comparison).

So I'd leave ids intact for the moment.

**Comment by justusjonas74** [comment]
In the early drafts of the spec (VDV 432) there wasn't any information about the leading zero. So some providers used an ID without leading zero. Now they have to change their IDs, but some didn't so far.
